document.addEventListener('DOMContentLoaded', async () => {
  const target = document.querySelector('#product-detail');
  if (!target) return;

  try {
    const response = await fetch('../data/products.json');
    if (!response.ok) throw new Error('Unable to load products.');
    const products = await response.json();
    const requestedId = Number(new URLSearchParams(location.search).get('id'));
    const product = products.find((item) => item.id === requestedId) || products[0];
    if (!product) throw new Error('No products are available.');
    document.title = `${product.name} | SHOP.CO`;
    renderProduct(target, product, products);
  } catch (error) {
    target.innerHTML = `<p class="product-error">${error.message} Please try again.</p>`;
  }
});

function renderProduct(target, product, products) {
  const images = (product.images || []).map(resolveProductImage).filter(Boolean);
  const primaryImage = images[0] || '../images/T-shirt_With_Tape_Details.png';
  const colors = product.colors?.length ? product.colors : ['black'];
  const sizes = product.sizes?.length ? product.sizes : ['One Size'];
  const related = [...products.filter((item) => item.id !== product.id && item.category === product.category), ...products.filter((item) => item.id !== product.id && item.category !== product.category)].slice(0, 4);
  let selectedColor = colors[0];
  let selectedSize = sizes[0];
  let quantity = 1;

  target.innerHTML = `
    <p class="product-breadcrumb">Home <span>›</span> Shop <span>›</span> ${product.gender || 'Collection'} <span>›</span> ${product.category || 'Products'}</p>
    <section class="product-main">
      <div class="product-gallery"><div class="product-thumb-list">${images.map((image, index) => `<button type="button" class="${index === 0 ? 'active' : ''}" data-image="${image}" aria-label="View ${product.name} image ${index + 1}"><img src="${image}" alt="${product.name} view ${index + 1}" /></button>`).join('') || `<button type="button" class="active"><img src="${primaryImage}" alt="${product.name}" /></button>`}</div><div class="product-main-visual"><img id="main-product-image" src="${primaryImage}" alt="${product.name}" /></div></div>
      <div class="product-info"><h1 class="product-title">${escapeHtml(product.name)}</h1><div class="rating-row"><span class="stars" aria-label="${product.rating || 0} out of 5">${starRating(product.rating)}</span><span class="rating-score">${product.rating || 0}/5</span></div><div class="product-price-row"><span class="product-price">$${product.price}</span>${product.originalPrice > product.price ? `<span class="product-old-price">$${product.originalPrice}</span>` : ''}${product.discount ? `<span class="product-discount">-${product.discount}%</span>` : ''}</div><p class="product-description">${escapeHtml(product.description || 'A versatile piece made for everyday wear.')}</p><div class="option-group"><span class="product-label">Select Colors</span><div class="swatches">${colors.map((color, index) => `<button type="button" class="swatch ${index === 0 ? 'active' : ''}" data-color="${escapeHtml(color)}" style="background:${color};" aria-label="Select ${escapeHtml(color)}"></button>`).join('')}</div></div><div class="option-group"><span class="product-label">Choose Size</span><div class="size-row">${sizes.map((size, index) => `<button type="button" class="size-option ${index === 0 ? 'active' : ''}" data-size="${escapeHtml(size)}">${escapeHtml(size)}</button>`).join('')}</div></div><div class="purchase-row"><div class="quantity-box"><button type="button" data-quantity="-1" aria-label="Decrease quantity">−</button><span id="product-quantity">1</span><button type="button" data-quantity="1" aria-label="Increase quantity">+</button></div><button type="button" class="add-to-cart-btn" id="add-to-cart">Add to Cart</button></div><p id="cart-feedback" class="cart-feedback" aria-live="polite"></p></div>
    </section>
    <section class="product-tabs"><button type="button" class="product-tab active" data-panel="details">Product Details</button><button type="button" class="product-tab" data-panel="reviews">Rating &amp; Reviews</button><button type="button" class="product-tab" data-panel="faqs">FAQs</button></section>
    <section id="product-tab-content" class="tab-content">${detailsMarkup(product)}</section>
    <section class="related-section"><h2 class="related-title">You might also like</h2><div class="related-grid">${related.map((item) => `<article class="related-card"><a href="product.html?id=${item.id}"><img src="${resolveProductImage(item.images?.[0])}" alt="${escapeHtml(item.name)}" /><h4>${escapeHtml(item.name)}</h4><div class="related-pricing"><span class="related-price">$${item.price}</span>${item.originalPrice > item.price ? `<span class="related-old-price">$${item.originalPrice}</span>` : ''}</div></a></article>`).join('')}</div></section>`;

  target.querySelectorAll('.product-thumb-list button[data-image]').forEach((button) => button.addEventListener('click', () => { target.querySelector('#main-product-image').src = button.dataset.image; target.querySelectorAll('.product-thumb-list button').forEach((item) => item.classList.remove('active')); button.classList.add('active'); }));
  target.querySelectorAll('.swatch').forEach((button) => button.addEventListener('click', () => { selectedColor = button.dataset.color; target.querySelectorAll('.swatch').forEach((item) => item.classList.remove('active')); button.classList.add('active'); }));
  target.querySelectorAll('.size-option').forEach((button) => button.addEventListener('click', () => { selectedSize = button.dataset.size; target.querySelectorAll('.size-option').forEach((item) => item.classList.remove('active')); button.classList.add('active'); }));
  target.querySelectorAll('[data-quantity]').forEach((button) => button.addEventListener('click', () => { quantity = Math.max(1, quantity + Number(button.dataset.quantity)); target.querySelector('#product-quantity').textContent = quantity; }));
  target.querySelector('#add-to-cart').addEventListener('click', () => { const cart = ShopStorage.getCart(); const entry = cart.find((item) => item.id === product.id && item.size === selectedSize && item.color === selectedColor); if (entry) entry.quantity += quantity; else cart.push({ ...product, image: product.images?.[0] || '', size: selectedSize, color: selectedColor, quantity }); ShopStorage.setCart(cart); updateCartCount(); target.querySelector('#cart-feedback').textContent = `${quantity} item${quantity > 1 ? 's' : ''} added to your cart.`; });
  target.querySelectorAll('.product-tab').forEach((button) => button.addEventListener('click', () => { target.querySelectorAll('.product-tab').forEach((item) => item.classList.remove('active')); button.classList.add('active'); const content = target.querySelector('#product-tab-content'); content.innerHTML = button.dataset.panel === 'details' ? detailsMarkup(product) : button.dataset.panel === 'reviews' ? reviewsMarkup(product) : faqsMarkup(); if (button.dataset.panel === 'reviews') bindReviewForm(content, product); }));
}

function detailsMarkup(product) { return `<div class="details-panel"><h3>Product details</h3><ul>${(product.details || ['Made with quality materials.']).map((detail) => `<li>${escapeHtml(detail)}</li>`).join('')}</ul><p>In stock: ${product.stock ?? 'Available'}</p></div>`; }
function reviewsMarkup(product) { const savedReviews = JSON.parse(localStorage.getItem('shop-co-reviews') || '[]'); return `<div class="review-panel"><div class="review-header"><h3>All Reviews <span class="tag">${(product.reviewCount || 0) + savedReviews.length}</span></h3><button class="write-review" type="button">Write a Review</button></div><form class="review-form" hidden><div><label for="product-review-name">Your name</label><input id="product-review-name" name="name" maxlength="40" required placeholder="Enter your name" /></div><fieldset class="star-picker"><legend>Your rating</legend><div>${[5, 4, 3, 2, 1].map((rating) => `<input type="radio" id="product-star-${rating}" name="rating" value="${rating}" ${rating === 5 ? 'checked' : ''} /><label for="product-star-${rating}" title="${rating} stars">★</label>`).join('')}</div></fieldset><div><label for="product-review-text">Your review</label><textarea id="product-review-text" name="review" maxlength="500" required placeholder="Tell us what you think"></textarea></div><div class="review-form-actions"><button class="cancel-review" type="button">Cancel</button><button type="submit">Post Review</button></div></form><div class="review-grid">${savedReviews.map(sharedReviewCard).join('')}<article class="review-card"><div class="review-top"><span class="review-user">Shopper review</span><span class="review-stars">${starRating(product.rating)}</span></div><p>Customers rate this product ${product.rating || 0} out of 5 based on ${product.reviewCount || 0} reviews.</p></article></div></div>`; }
function bindReviewForm(content, product) { const form = content.querySelector('.review-form'); content.querySelector('.write-review').addEventListener('click', () => { form.hidden = false; form.querySelector('input').focus(); }); content.querySelector('.cancel-review').addEventListener('click', () => { form.reset(); form.hidden = true; }); form.addEventListener('submit', (event) => { event.preventDefault(); const values = new FormData(form); const review = { name: values.get('name').trim(), copy: values.get('review').trim(), rating: Number(values.get('rating')), date: new Intl.DateTimeFormat('en-US', { month: 'long', day: 'numeric', year: 'numeric' }).format(new Date()) }; const reviews = JSON.parse(localStorage.getItem('shop-co-reviews') || '[]'); reviews.unshift(review); localStorage.setItem('shop-co-reviews', JSON.stringify(reviews)); content.innerHTML = reviewsMarkup(product); bindReviewForm(content, product); }); }
function sharedReviewCard(review) { const rating = Math.min(5, Math.max(1, Number(review.rating) || 5)); return `<article class="review-card"><div class="review-top"><span class="review-user">${escapeHtml(review.name)} <span style="color:#13a04b">●</span></span><span class="review-stars">${'★'.repeat(rating)}${'☆'.repeat(5 - rating)}</span></div><p>"${escapeHtml(review.copy)}"</p><span class="review-date">Posted on ${escapeHtml(review.date)}</span></article>`; }
function faqsMarkup() { return '<div class="details-panel"><h3>Frequently asked questions</h3><p>Orders are processed securely. Choose your preferred size and color before adding an item to your cart.</p></div>'; }
function starRating(rating = 0) { return '★'.repeat(Math.round(rating)) + '☆'.repeat(5 - Math.round(rating)); }
function escapeHtml(value) { return String(value ?? '').replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' })[character]); }
